apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aaa-proj-s3
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: aaa s3
  sourceRepos:
  - '*'

  destinations:
  - namespace: 'aaa'
    server: 'https://kubernetes.default.svc'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

  roles:
  - name: read-only
    description: Read-only privileges to aaa-proj-s3
    policies:
    - p, proj:aaa-proj-s3:read-only, applications, get, aaa-proj-s3/*, allow
    groups:
    - af374b7d-bc8a-4268-b61d-6453dfaac476

