apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: bbb-proj-s3
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: bbb s3
  sourceRepos:
  - '*'

  destinations:
  - namespace: 'bbb'
    server: 'https://kubernetes.default.svc'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'

  roles:
  - name: read-only
    description: Read-only privileges to bbb-proj-s3
    policies:
    - p, proj:bbb-proj-s3:read-only, applications, get, bbb-proj-s3/*, allow
    groups:
    - cd27ab64-739a-424d-a8f7-f9d6316a885b
